version: '3.2'

services:
  php:
    platform: ${BUILDPLATFORM}
    build:
      context: ./docker/php
      args:
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    working_dir: /app
    volumes:
      - ./docker/php/base.ini:/usr/local/etc/php/conf.d/base.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.composer-docker/cache:/var/www/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/php/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint
      - ./docker/php/.bashrc:/var/www/.bashrc
    environment:
      PHP_USER_ID: ${PHP_USER_ID}
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      TZ: ${TIMEZONE}
      DEBIAN_FRONTEND: noninteractive
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - db
    profiles:
      - core
    restart: ${RESTART}

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app:delegated
    depends_on:
      - php
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx-kma.rule: "Host(`${DOMAIN}`)"
    networks:
      - default
      - web
    profiles:
      - core
    restart: ${RESTART}

  supervisor:
    platform: ${BUILDPLATFORM}
    build:
      context: ./docker/supervisor
      args:
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    working_dir: /app
    volumes:
      - ./docker/php/base.ini:/usr/local/etc/php/conf.d/base.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.composer-docker/cache:/var/www/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf:ro
    environment:
      PHP_USER_ID: ${PHP_USER_ID}
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      TZ: ${TIMEZONE}
      DEBIAN_FRONTEND: noninteractive
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - db
      - rabbitmq
    profiles:
      - core
    restart: ${RESTART}

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: ${TIMEZONE}
      DEBIAN_FRONTEND: noninteractive
    volumes:
      - db_data:/var/lib/mariadb
    ports:
      - 127.0.0.1:${DOCKER_DB_PORT}:3306
    profiles:
      - core

  rabbitmq:
    platform: ${BUILDPLATFORM}
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    labels:
      traefik.enable: "true"
      traefik.http.services.rabbitmq-kma.loadbalancer.server.port: "15672"
      traefik.http.routers.rabbitmq-kma.rule: "Host(`rabbit.${DOMAIN}`)"
      traefik.http.routers.rabbitmq-kma.tls: "false"
      traefik.http.routers.rabbitmq-kma.service: "rabbitmq-kma"
    networks:
      - default
      - web
    profiles:
      - core
    restart: ${RESTART}

  phpmyadmin:
    platform: ${BUILDPLATFORM}
    image: phpmyadmin:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.phpmyadmin-kma.rule: "Host(`pma.${DOMAIN}`)"
    environment:
      PMA_HOST: db
      TZ: ${TIMEZONE}
      DEBIAN_FRONTEND: noninteractive
    networks:
      - default
      - web
    depends_on:
      - db
    profiles:
      - dev
    restart: ${RESTART}

volumes:
  db_data:
  rabbitmq_data:

networks:
  web:
    external: true